- name: "disable ipv6 in ubuntu playbook"
  hosts: "lab"
  become: true
  become_method: sudo
  gather_facts: false
  tasks:

    - name: Test for exist disable ipv6
      shell: grep -c "^net.ipv6.conf.all.disable_ipv6 = 1"  || true
      register: test_ipv6

    - name: disable ipv6
      lineinfile:
        dest: /etc/sysctl.conf
        line: net.ipv6.conf.all.disable_ipv6 = 1
      when: test_ipv6.stdout == "0"